name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Adjust as per your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'  # Use the PHP version from your Dockerfile

      - name: Install Composer dependencies
        run: |
          composer install --no-ansi --no-interaction --no-progress --no-scripts --optimize-autoloader
          cp .env.example .env
          php artisan key:generate

      - name: Build and run Docker containers with Laravel Sail
        run: |
          curl -s https://laravel.build/sail | bash
          ./vendor/bin/sail up -d
          ./vendor/bin/sail artisan sail:install  # Install Laravel Sail if not already installed
          ./vendor/bin/sail artisan migrate --force  # Run database migrations
          ./vendor/bin/sail artisan storage:link  # Ensure storage link is created

      - name: Fix permissions
        run: |
          ./vendor/bin/sail exec --user=root laravel.test chown -R www-data:www-data /var/www/html
          ./vendor/bin/sail exec --user=root laravel.test chmod -R 775 /var/www/html/storage
          chmod -R 775 storage bootstrap/cache  # Additional permissions for Laravel

      - name: Run tests (if applicable)
        run: |
          ./vendor/bin/sail test

      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          php artisan config:cache  # Clear and cache config
          php artisan route:cache  # Cache routes
          php artisan view:cache   # Cache views
          php artisan event:cache  # Cache events
          php artisan vendor:publish --tag=public --force  # Publish public assets
          ./vendor/bin/sail artisan octane:start --port=8080
