name: Deploy Laravel Sail Project

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql/mysql-server:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: contactlistdb
          MYSQL_USER: sail
          MYSQL_PASSWORD: password
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install Composer dependencies
        run: composer install --no-dev --prefer-dist --no-progress --no-suggest

      - name: Start MySQL service
        run: docker-compose up -d mysql

      - name: Wait for MySQL to be ready
        run: |
          timeout 1m bash -c 'until echo > /dev/tcp/localhost/3306; do sleep 30; done'

      - name: Verify MySQL connection
        run: php -r "if (!@mysqli_connect('127.0.0.1', 'sail', 'password', 'contactlistdb', 3306)) { echo 'MySQL is not accessible'; exit(1); }"

      - name: Deploy application
        run: |
          php artisan migrate --force
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache

      - name: Stop MySQL service
        run: docker-compose down
