name: Deploy Laravel Sail Project

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql/mysql-server:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: contactlistdb
          MYSQL_USER: sail
          MYSQL_PASSWORD: password
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

      redis:
        image: redis:alpine
        ports:
          - 6379:6379

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Copy .env.example to .env
        run: cp .env.example .env

      - name: Install Composer dependencies
        run: composer install --no-dev --prefer-dist --no-progress --no-suggest

      - name: Start Laravel Sail containers
        run: |
          php artisan sail:install --with=mysql,redis
          vendor/bin/sail up -d

      - name: Run migrations and cache configurations
        run: |
          vendor/bin/sail artisan migrate --force
          vendor/bin/sail artisan config:cache
          vendor/bin/sail artisan route:cache
          vendor/bin/sail artisan view:cache

      - name: Stop Laravel Sail containers
        run: vendor/bin/sail down
