name: Deploy Laravel Sail Project

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql/mysql-server:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: contactlistdb
          MYSQL_USER: sail
          MYSQL_PASSWORD: password
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

      redis:
        image: redis:alpine
        ports:
          - 6379:6379

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy .env.example to .env
        run: cp .env.example .env

      - name: Install Composer dependencies
        run: composer install --no-dev --prefer-dist --no-progress --no-suggest

      - name: Start MySQL and Redis containers
        run: |
          docker-compose up -d mysql redis

      - name: Run migrations and cache configurations
        run: |
          docker-compose exec -T mysql mysql -usail -ppassword -e "CREATE DATABASE IF NOT EXISTS contactlistdb;"
          docker-compose exec -T mysql php artisan migrate --force
          docker-compose exec -T mysql php artisan config:cache
          docker-compose exec -T mysql php artisan route:cache
          docker-compose exec -T mysql php artisan view:cache

      - name: Stop containers
        run: docker-compose down
