name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Adjust as per your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'  # Use the PHP version from your Dockerfile

      - name: Install Composer dependencies
        run: |
          composer install --no-ansi --no-interaction --no-progress --no-scripts --optimize-autoloader
          cp .env.example .env
          php artisan key:generate

      - name: Build and run Docker containers with Laravel Sail
        run: |
          curl -s https://laravel.build/sail | bash
          ./vendor/bin/sail up -d

      - name: Run tests (if applicable)
        run: |
          ./vendor/bin/sail test

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public  # Adjust if your Laravel public directory is different
