name: Deploy Laravel Sail Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: contactlistdb
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml, curl, zip, pdo, pdo_mysql, redis

      - name: Set up Laravel Sail
        run: composer require laravel/sail --dev

      - name: Install dependencies
        run: composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts

      - name: Copy .env.example to .env
        run: cp .env.example .env

      - name: Generate application key
        run: php artisan key:generate

      - name: Start Laravel Sail containers
        run: |
          php artisan sail:install
          ./vendor/bin/sail up -d

      - name: Wait for MySQL to start
        run: dockerize -wait tcp://localhost:3306 -timeout 1m

      - name: Run database migrations
        run: php artisan migrate --force

      - name: Run tests (if applicable)
        run: php artisan test

      - name: Stop Laravel Sail containers
        run: ./vendor/bin/sail down

      - name: Deploy finished
        run: echo "Deployment successful"
