name: Laravel Sail CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker environment
      run: cp .env.example .env

    # Ensure public/storage directory exists (if not needed, remove this step)
    - name: Ensure public/storage directory exists
      run: |
        if [ ! -d "public/storage" ]; then
          mkdir -p public/storage
        fi

    - name: Start Laravel Sail
      run: ./vendor/bin/sail up -d

    - name: Install Composer dependencies
      run: ./vendor/bin/sail composer install --optimize-autoloader

    - name: Generate application key
      run: ./vendor/bin/sail artisan key:generate

    - name: Run database migrations
      run: ./vendor/bin/sail artisan migrate --force

    - name: Seed the database (if needed)
      run: ./vendor/bin/sail artisan db:seed --force

    - name: Build assets (if applicable)
      run: ./vendor/bin/sail npm install && ./vendor/bin/sail npm run production

    - name: Run tests (if applicable)
      run: ./vendor/bin/sail test

    - name: Deploy to GitHub Pages (if applicable)
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public

    - name: Stop Laravel Sail
      run: ./vendor/bin/sail down
