name: Laravel Sail CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    services:
      laravel.test:
        image: sail-8.2/app  # Specify PHP 8.2 image for Sail
        build:
          context: ./vendor/laravel/sail/runtimes/8.2  # Adjust path to match your Sail version
          dockerfile: Dockerfile
          args:
            WWWGROUP: '1000'
        ports:
          - '8080:80'
        environment:
          WWWUSER: '1000'
          LARAVEL_SAIL: 1
          XDEBUG_MODE: 'off'  # Adjust as per your debugging needs
        volumes:
          - './:/var/www/html'
          - './vendor:/var/www/html/vendor'
        networks:
          - sail
        options: --health-cmd="php-fpm --test" --health-interval=10s --health-timeout=5s --health-retries=3

      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: sail
          MYSQL_USER: sail
          MYSQL_PASSWORD: password
        ports:
          - '3306:3306'
        networks:
          - sail

      redis:
        image: redis:alpine
        ports:
          - '6379:6379'
        networks:
          - sail

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Copy .env.example to .env
        run: cp .env.example .env

      - name: Install Composer dependencies
        run: |
          curl -s https://getcomposer.org/installer | php
          php composer.phar install --no-ansi --no-interaction --no-progress --optimize-autoloader

      - name: Generate application key
        run: php artisan key:generate

      - name: Cache configuration
        run: php artisan config:cache

      - name: Run database migrations
        run: php artisan migrate --force

      - name: Start Laravel Sail
        run: ./vendor/bin/sail up -d

      - name: Install NPM dependencies (if applicable)
        run: ./vendor/bin/sail npm install --production

      - name: Build assets (if applicable)
        run: ./vendor/bin/sail npm run production

      - name: Test your application (if applicable)
        run: ./vendor/bin/sail test

      - name: Optimize Laravel application
        run: php artisan optimize

      - name: Route caching
        run: php artisan route:cache

      - name: View caching
        run: php artisan view:cache

      - name: Stop Laravel Sail
        run: ./vendor/bin/sail down
